Import('env')

test_env = env.Clone()

test_env.Append(CPPPATH=['../include'])
test_env.Append(CPPFLAGS='-D__UNIT_TESTING_ON')

test_framework = test_env.FindFile('libboost_unit_test_framework.a', env['LIBPATH'])

cfg_o = test_env.Object('test_cfg.o', '../src/cfg.cpp')

if(test_framework):
  test_env.Program('test_swordfish', [Glob('*.cpp'), cfg_o, test_framework])
else:
  print 'scons: failed to find the boost unit test framework!'
